// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdcwyqphuwdqzpqvacgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkY3d5cXBodXdkcXpwcXZhY2djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NTUzNTMsImV4cCI6MjA1NjUzMTM1M30.8JNDgdkCU6UAenCHalQkB0j3myRUIBAmdUAF7d2p40Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);